### ISSUE TITLE
Confusing diagram

### ISSUE THREAD

**Issue by lawsie** [raspberrypilearning/physical-computing-with-python#12]
I think this diagram is unnecessarily confusing:
https://github.com/raspberrypilearning/physical-computing-with-python/blob/master/images/camjam1wiring.png

Why are the negative legs of the LEDs in the positive rail? I know it doesn't make any difference practically, but that's going to confuse people. Do you agree @bennuttall as it was your original commit?

**Comment by bennuttall** [comment]
It makes sense to position the components on the breadboard like that because the buzzer can sit in the ground rail. It can't stretch between the outside rail and the middle rows, so it has to go on the inner rail. Unfortunately, without turning the breadboard upside-down, you have to use the positive rail for ground, which is ok. Could be slightly confusing but people should known/learn that the +/- rails are just labels, and they are whatever you designate them to be. Here, we've coloured the rail black to further indicate that it's negative.

What do you think?

**Comment by lawsie** [comment]
Couldn't the buzzer (and the rest of the components) be positioned on the left of the breadboard though, where the labelled ground rail is right next to the rows? Is there a reason they are all on the right?

**Comment by bennuttall** [comment]
But then you'd have wires crossing over the components. It's really clear this way.

**Comment by MarcScott** [comment]
Can I suggest that we get Sam to rotate the breadboard. On the other side, the negative rail is closest to the components, so the legs would all feed into a negative rail.
